name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

        
    # Install LaTeX dependencies for PDF build
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

    # Build the documentation
    - name: Build PDF
      run: |
        jupyter-book build . --builder pdflatex
        pdoc --math ./notebooks/enclose.py -o ./docs

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html

